# Generated by Django 4.0.3 on 2022-03-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='category',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='picture_path',
            field=models.CharField(default='default-picture.jpg', max_length=500),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
