# Generated by Django 4.0.3 on 2022-03-26 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_remove_ingredient_category_ingredient_picture_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='picture_path',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to=settings.AUTH_USER_MODEL),
        ),
    ]
