# Generated by Django 4.0.3 on 2022-04-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_ingredient_picture_path_ingredient_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='process',
            field=models.TextField(max_length=1000),
        ),
    ]
